version: '3'
services:
  api:
    image: golang:1.13
    container_name: accware_api
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    - ./data:/var/lib/accware
    - ./schema.sql:/usr/share/accware/schema.sql
    - ./assets:/usr/share/accware/assets
    working_dir: /app
    ports:
    - "8080:8080"
    command: [go, run, .]
    environment:
      PORT: "8080"
    env_file:
    - dev.env
