version: '3'
services:
  api:
    image: golang:1.13
    container_name: accware_api
    volumes:
    - /private/var/lib/accware:/var/lib/accware
    - /private/etc/accware:/etc/accware
    - ./api:/app
    - ./api/cache/mod:/go/pkg/mod
    - ./api/cache/go-build:/root/.cache/go-build
    working_dir: /app
    ports:
    - "8080:80"
    command: [go, run, .]
  ui:
    image: nginx:1.17
    container_name: accware_ui
    volumes:
    - ./ui/build:/usr/share/nginx/html
    - ./ui/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "3000:443"
