version: '3'
services:
  api:
    image: golang:1.13
    container_name: accware_api
    volumes:
    - ./api:/app
    - ./api/cache/mod:/go/pkg/mod
    - ./api/cache/go-build:/root/.cache/go-build
    - ./etc/accware:/etc/accware
    - ./data:/var/lib/accware
    working_dir: /app
    ports:
    - "8080:80"
    networks:
    - accware
    command: [go, run, .]
  ui:
    image: nginx:1.17
    container_name: accware_ui
    volumes:
    - ./ui/build:/usr/share/nginx/html
    - ./ui/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/auth.conf:/etc/nginx/auth.conf
    - ./etc/pki/nginx:/etc/pki/nginx
    networks:
    - accware
    links:
    - "api:accware-api"
    ports:
    - "3000:443"
networks:
  accware:
